-- Create a permanent user account
-- Note: This creates the user directly in the auth system
INSERT INTO auth.users (
  id,
  instance_id,
  email,
  encrypted_password,
  email_confirmed_at,
  created_at,
  updated_at,
  email_change_sent_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  role,
  aud,
  confirmation_token,
  email_change,
  email_change_confirm_status,
  banned_until,
  recovery_token,
  email_change_token_new,
  email_change_token_current,
  phone_change_token,
  phone_change,
  phone_change_sent_at,
  confirmed_at,
  invited_at,
  action_link,
  phone,
  phone_confirmed_at,
  recovery_sent_at,
  encrypted_password_nonce
) VALUES (
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000000',
  'andymelvin56@gmail.com',
  crypt('Themanthathadkilledme123!', gen_salt('bf')),
  now(),
  now(),
  now(),
  null,
  '{"provider": "email", "providers": ["email"]}',
  '{}',
  false,
  'authenticated',
  'authenticated',
  '',
  '',
  0,
  null,
  '',
  '',
  '',
  '',
  '',
  null,
  now(),
  null,
  '',
  null,
  null,
  null,
  null
);